mA/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myapp.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from django.conf import settings


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)

		user.fonction = 'C'
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.fonction = "A"
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


FONCTION = (
	('A','SOUS DIRECTEUR PERSONNEL'),
	('C','CHEF ATS')
)

class Utilisateur(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    numero = models.CharField(max_length=10)
    fonction = models.CharField(max_length=1,choices=FONCTION,null=False)
    profile_pic = models.ImageField(default="profile.jpg", null=True, blank=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)



    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    def __str__(self):
	    return self.username

	# For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, obj=None):
	    return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
	    return True



FONCTION2 = (
    ('R','rien'),
    ('D',"directeur"),
    ('DA','directeur adjoint'),
    ('SD','sous-directeur'),
    ('SDF','sous-directeur de finances')
)

SITUATION_FAMILIALE = (
    ('C','celibataire'),
    ('M','marié'),
    ('D',"devorcé")
)

NATURE = (
    ('S','stagiaire'),
    ('F','fonctionnaire')
)


MOTIF = (
    ('N','None'),
    ('DE','Décédé'),
    ('M','Mutation'),
    ('DI','Dimensionné'),
    ('R','Retraité')
)

DECISION = (
    ('N','None'),
    ('A','Automatique'),
    ('C','Commission')
)

ALERT = (
    ('0','0'),
    ('1',"1 an"),
    ('2','2 ans'),
    ('3','3 ans'),
    ('4','4 ans'),
    ('5','5 ans'),
    ('6','6 ans'),
)

class Employee(models.Model):
    image = models.ImageField(default="profile.jpg", null=True, blank=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    function=models.CharField(choices=FONCTION2 , max_length=3,null=True)
    numero =models.CharField(max_length=10,null=True)
    naissance=models.DateField()
    adresse = models.CharField(max_length=200,null=True)
    email = models.EmailField(max_length=200,null=True)
    situation = models.CharField(choices=SITUATION_FAMILIALE , max_length=1,null=True)
    # date recrutememtn
    date_joined = models.DateField()
    date_recretment  = models.DateField()
    Nenfant=models.IntegerField()
    nature=models.CharField(choices=NATURE , max_length=1,null=True)
    numccp=models.IntegerField()
    numss=models.IntegerField()
    Xfonctionnair = models.BooleanField(default=False)
    motif = models.CharField(default="N", choices=MOTIF,max_length=2)
    date_supression = models.DateField(auto_now_add=True,null=True,blank=True)
    comentaire = models.TextField(null=True,blank=True)
    date_effet = models.DateField(blank=True,null=True)
    cheked = models.BooleanField(default=False)
    is_greater_than_2 = models.BooleanField(default=False)
    is_greater_than_10 = models.BooleanField(default=False)
    decision = models.CharField(default="N",max_length=1,choices=DECISION) 
    color = models.CharField(max_length=10,null=True,blank=True)
    checked = models.BooleanField(default=False)
    date = models.DateField(blank=True,null=True)
    alerte = models.CharField(default="0", max_length=1,choices=ALERT)
    def __str__(self):
        return self.nom

FILIERE = (
        ('0','Filiere'),
        ('A','Administration'),
        ('I','Informatique'),
    )

GRADES = (
    # default
    ('0','Grade'),
    # Adminitration
    ('GA','Adimistrateur'),
    ('GAP','Administrateur principal'),
    ('GAC','Administrateur conseiller'),
    ('GAA',"Attaché d'administration"),
    ('GPA',"Attaché principale d'administration"),
    ('AB',"Agents de bureau"),
    ('AA',"Agent d'administration"),
    ('APA',"Agent principale d'administration"),
    ('AS',"Agents de saisie"),
    ('S',"Secretaire"),
    ("SD","Secretaire de direction"),
    ('SPD',"Secretaire principale de direction"),
    ('ACA',"Aide comptable administrative"),
    ("CA","Compatble administrative"),
    ('CAP',"Comptable administrative principale"),
    #Informatique
    ("IA","Ingenieur d'application"),
    ("IE","Ingenieur d'etat"),
    ("IP","Ingenieur principal"),
    ("IC","Ingenieur en chef"),
    ("T","Technicien"),
    ("TS","Technicien superieur"),
    ("AT","Adjoint technique"),
    ("AST","Agent technique")
)

CORPS = (
    # default
    ("0","COPRS"),
    #admnisi
    ("A","Adminstrateurs"),
    ("AD","Attachés d'dministrations"),
    ("AA","Agents d'dministrations"),
    ("S","Secretaire"),
    ("CA","Comptables administratifs"),
    # info
    ("I","Ingenieurs"),
    ("T","Techniciens"),
    ("AT","Adjoint techniques"),
    ("AST","Agents techniques"),
)



POSTES = (
    ('R','Rien'),
    ('D','Directeur'),
    ('DA','Directeur adjoint'),
    ('CD','Chef de departement'),
    ('SG','Secretaire generale'),
    ('DB','Directeur de la bibliotheque'),
    ('SDPF','Sous directeur des personnels et de la formation'),
    ('SDFM','Sous directeur des finances et de moyens'),
    ('RCIA',"Responsable de centre d'impression et d'audiovisuel"),
    ('RCSI',"Responsable de centre de systemes et reseaux d'informations"),
    ("RHT","Responsable de hall de technologies"),
    ("RFP","Responsable de la forme de production")
)

PROMO = (
    ('0','0'),
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
    ('13','13'),
    ('14','14'),
    ('15','15'),
    ('16','16'),
)

ECHELON = (
    ('0','0'),
    ('1','1er'),
    ('2','2eme'),
    ('3','3eme'),
    ('4','4eme'),
    ('5','5eme'),
    ('6','6eme'),
    ('7','7eme'),
    ('8','8eme'),
    ('9','9eme'),
    ('10','10eme'),
    ('11','11eme'),
    ('12','12eme'),
)

class Paie(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    filiere = models.CharField(default='0',max_length=1,choices=FILIERE)
    grade = models.CharField(default="0",max_length=3,choices=GRADES)
    corps = models.CharField(default="0",max_length=3,choices=CORPS)
    categorie = models.IntegerField(default=0)
    indice = models.IntegerField(default=0)
    salaire = models.FloatField(default=0.0)
    poste_occupe = models.CharField(default='R',max_length=4,choices=POSTES)
    indiciaire = models.FloatField(default=0.0)
    categorie_promo = models.CharField(default="0",max_length=2,choices=PROMO)
    groupe = models.CharField(default="None",max_length=10)
    indice_minimale = models.FloatField(default=0.0)
    indice_echelon = models.CharField(default="0",max_length=2,choices=ECHELON)
    echelon = models.IntegerField(default=0)
    grille = models.FloatField(default=0.0) 
    indemite_sac = models.FloatField(default=0.0)   
    indemite_stc = models.FloatField(default=0.0)
    securite = models.FloatField(default=0.0)
    salaire_brut = models.FloatField(default=0.0)
    indimnite_transport = models.IntegerField(default=0)
    indimnite_panier = models.IntegerField(default=0)
    totale_brute_imposable_irg = models.FloatField(default=0.0)
    irg = models.IntegerField(default=0)
    allocation_familiale = models.IntegerField(default=0)
    totale = models.FloatField(default=0.0)
    nombre_travaille = models.IntegerField(default=0)
    nombre_absence = models.IntegerField(default=0)
    salaire_net = models.FloatField(default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.employee.nom




NATUREC = (
    ('M','Maladie'),
    ('A','Annuel'),
    ('E','Exceptionnel')
)

class Conge(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    debut = models.DateField(null=True,blank=True)
    fin = models.DateField(null=True,blank=True)
    nombre = models.CharField(max_length=50,null=True,blank=True)
    nature = models.CharField(null=True,blank=True,max_length=1,choices=NATUREC)
    retour = models.DateTimeField(null=True,blank=True)
    commentaire = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.employee.nom



TRIMESTRE = (
    ("1","1er trimestre"),
    ("2","2eme trimestre"),
    ('3','3eme trimestre'),
    ('4',"4eme trimestre")
)


class Prime(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    note_prime = models.IntegerField(blank=True,null=True)
    commentaire = models.TextField(blank=True,null=True)
    trimestre = models.CharField(max_length=1,choices=TRIMESTRE,blank=True,null=True)
    date = models.DateField(blank=True,null=True)
    salaire_principal = models.FloatField() 
    salaire_brut_mensulle = models.FloatField() 

templates/ajoutUtilisateurs.html
{% extends 'main.html' %} {% block body %}
<div class="container ajout" style="height: auto">
  <form enctype="multipart/form-data" action="{% url 'ajout' %}" method="POST">
    {% csrf_token %}
    <div class="banner">
      <h1>Espace un utilisateur</h1>
    </div>
    <!-- first -->
    <div class="row">
      <div class="col">
        <input
          type="text"
          class="form-control"
          placeholder="Nom"
          name="nom"
          required
        />
      </div>
      <div class="col">
        <input
          type="text"
          class="form-control"
          placeholder="Prenom"
          name="prenom"
          required
        />
      </div>
    </div>
    <!--second-->
    <div class="row">
      <div class="col">
        <input
          type="text"
          class="form-control"
          placeholder="Pseudo-nom"
          name="username"
          required
        />
      </div>
      <div class="col">
        <input
          type="text"
          class="form-control"
          placeholder="Email"
          name="email"
          required
        />
      </div>
    </div>
    <!--third-->
    <div class="row">
      <div class="col">
        <input
          type="text"
          class="form-control"
          placeholder="Numero"
          name="numero"
          required
        />
      </div>
      <div class="col">
        <select class="form-select" name="fonction">
          <option selected>Fonction</option>
          <option value="A">ADMIN</option>
          <option value="C">CHEF ATS</option>
        </select>
      </div>
    </div>
    <!--password-->
    <div class="row">
      <div class="col">
        <input
          type="password"
          class="form-control"
          placeholder="mote de passe"
          name="password"
          required
        />
      </div>
      <div class="col">
        <input
          type="password"
          class="form-control"
          placeholder="confimer mote de passe"
          name="password2"
          required
        />
      </div>
    </div>
    <!--Image-->
    <div class="row">
      <div class="form-group" style="text-align: center">
        {{form.profile_pic}}
      </div>
    </div>
    <!--valide-->
    <div
      class="row"
      style="display: flex; justify-content: center; aligntu-items: center"
    >
      <a
        style="width: auto"
        href="{% url 'users' %}"
        class="btn btn-danger mb-3 mx-2"
        >Annuler</a
      >
      <button
        style="width: auto"
        type="submit"
        class="btn btn-primary mb-3 mx-2"
      >
        Valider
      </button>
    </div>
  </form>
</div>
{% endblock %}

templates/employee.html
{% extends 'main.html' %} {%block title%}Espace ATS{%endblock%} {%block body%}
<div class="container home" style="height: 100%">
  <div class="row" style="margin-left: 3px">
    {% if fonctionnaire %}
    <small>
      <a href="{% url 'ats' %}" class="btn btn-primary">fonctionnaire</a>
    </small>
    {% else %}
    <small>
      <a href="{% url 'Xfonctionnaire' %}" class="btn btn-primary"
        >X-fonctionnaire</a
      >
    </small>
    {% endif %}
    <form action="{% url 'ats' %}" method="get">
      <div class="input-group search">
        <div class="form-outline">
          <input type="search" name="search" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </form>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">NOM</th>
          <th scope="col">PRENOM</th>
          {% if not fonctionnaire %}
          <th scope="col">FONCTION</th>
          <th scope="col">Date de rejoint</th>
          <th scope="col">SUPPRIMER</th>
          <th scope="col">MODIFIER</th>
          {% else %}
          <th scope="col">Date de suppresion</th>
          <th scope="col">Motif</th>
          <th scope="col">Commentaire</th>
          <th scope="col">SUPPRIMER</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr
          style="background-color:{{employee.color}}"
          class="tr"
          data-nom="{{employee.nom}}"
          data-prenom="{{employee.prenom}}"
          data-id="{{employee.id}}"
          data-image="{{employee.image.url}}"
          data-numero="{{employee.numero}}"
        >
          <td>{{employee.id}}</td>
          <td>{{employee.nom}}</td>
          <td>{{employee.prenom}}</td>
          {% if not fonctionnaire %}
          <td>{{employee.get_function_display}}</td>
          <td>{{employee.date_joined|date:"d/m/Y"}}</td>
          <td>
            <!--models-->
            <!-- Button trigger modal -->
            <button
              type="button"
              class="btn btn"
              data-bs-toggle="modal"
              data-bs-target="#employeeModel{{employee.id}}"
            >
              <i class="fa fa-trash" aria-hidden="true" style="color: red"></i>
            </button>

            <!-- Modal -->
            <div
              class="modal fade"
              id="employeeModel{{employee.id}}"
              tabindex="-1"
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div
                class="
                  modal-dialog modal-dialog-centered modal-dialog-scrollable
                "
              >
                <form
                  action="{% url 'supprimerats' employee.id %}"
                  method="POST"
                >
                  {% csrf_token %}
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="staticBackdropLabel">
                        Boite de la supression
                      </h5>
                      <button
                        type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"
                      ></button>
                    </div>
                    <div class="modal-body">
                      <!--first-->
                      <div class="row">
                        <div class="col">
                          <input
                            type="text"
                            class="form-control"
                            value="{{employee.nom}}"
                          />
                        </div>
                        <div class="col">
                          <input
                            type="text"
                            class="form-control"
                            value="{{employee.prenom}}"
                          />
                        </div>
                      </div>
                      <!--seconde-->
                      <div
                        class="row"
                        style="margin-top: 10px; margin-bottom: 10px"
                      >
                        <div class="col" style="text-align: initial">
                          <label class="form-label">Motif :</label>
                          <select class="form-select IE" name="motif">
                            <option selected>0</option>
                            <option value="DE">Décedé</option>
                            <option value="M">Mutation</option>
                            <option value="DI">Dimensionné</option>
                            <option value="R">Retraité</option>
                          </select>
                        </div>
                        <div class="col" style="text-align: initial">
                          <label class="form-label">Date de suppresion :</label>
                          <input
                            type="date"
                            class="form-control"
                            name="date_supression"
                            required
                          />
                        </div>
                      </div>
                      <!--third-->
                      <div class="row">
                        <div class="col">
                          <textarea
                            class="form-control"
                            placeholder="commentaire"
                            name="commentaire"
                            rows="3"
                          ></textarea>
                        </div>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button
                        type="button"
                        class="btn btn-secondary"
                        data-bs-dismiss="modal"
                      >
                        Annuler
                      </button>
                      <button type="Submit" class="btn btn-danger">
                        Confirmer
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </div>

            <!--fin models-->
          </td>
          <td>
            <a href="{% url 'editats' employee.id %}">
              <i class="fas fa-edit" style="color: green"></i>
            </a>
          </td>
          {% else %}
          <td>{{employee.date_supression | date:"d/m/Y"}}</td>
          <td>{{employee.get_motif_display}}</td>
          <td>{{employee.comentaire}}</td>
          <td>
            <!--start model-->
            <button
              type="button"
              class="btn btn"
              data-bs-toggle="modal"
              data-bs-target="#employeeModel{{employee.id}}"
            >
              <i class="fa fa-trash" aria-hidden="true" style="color: red"></i>
            </button>

            <!-- Modal -->
            <div
              class="modal fade"
              id="employeeModel{{employee.id}}"
              tabindex="-1"
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">
                      Confirmation de la supression
                    </h5>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      Annuler
                    </button>
                    <a
                      href="{% url 'suppats' employee.id %}"
                      class="btn btn-danger"
                    >
                      Confirmer
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <!--end-->
          </td>
          {% endif %}
        </tr>
        {% endfor %} {% if is_paginated %}
        <tr>
          <td colspan="7" class="table">
            <div
              style="
                display: flex;
                justify-content: center;
                align-items: center;
              "
            >
              {% if employees.has_previous %}
              <div>
                <a href="?page={{employees.previous_page_number}}">
                  <i class="fa fa-caret-left fa-2x" aria-hidden="true"></i>
                </a>
              </div>

              {% endif %}
              <div>
                <span style="background-color: #e8e5e5; border-radius: 20px"
                  >{{page_number}}</span
                >
              </div>

              <!--ll-->
              {% if employees.has_next %}
              <div>
                <a href="?page={{employees.next_page_number}}">
                  <i class="fa fa-caret-right fa-2x" aria-hidden="true"></i>
                </a>
              </div>

              {% endif %}
            </div>
          </td>
        </tr>

        {% endif %} {% if not fonctionnaire %}
        <tr>
          <td colspan="7" class="table-active add">
            <a href="{% url 'ajoutats' %}">
              <i class="fa fa-plus" aria-hidden="true"></i>
            </a>
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
  <div class="add"></div>
</div>
{% endblock%} {% block script %}
<script>
  document.querySelectorAll(".add").forEach((div) => {
    div.onclick = () => {
      window.location.href = "{% url 'ajoutats' %}";
    };
  });
  var isTrue = false;
  document.querySelectorAll(".tr").forEach((row) => {
    row.onclick = () => {
      if (!isTrue) {
        console.log(isTrue);
        document.querySelector(".rightbar").className = "rightbar2";
        isTrue = true;
      }
      document.querySelector(".home").style.width = "70%";
      document.querySelector(".user").src = row.dataset.image;
      /* name */
      document.querySelector(".nom").innerHTML =
        row.dataset.nom + " " + row.dataset.prenom;
      /* numero*/
      if ({{fonctionnaireJs}}) {
        document.querySelector(".paielink").href =
          "/ajoutpaie/" + row.dataset.id;
        document.querySelector(".congelink").href = "/conge/" + row.dataset.id;
        document.querySelector(".attestationpdf").href =
          "/pdf/attestation/" + row.dataset.id;
        document.querySelector(".titreConge").href =
          "/titreConge/" + row.dataset.id;

        document.querySelector(".prime").href = "/prime/" + row.dataset.id;
        document.querySelector(".fichePaie").href =
          "/pdf/paie/" + row.dataset.id;
        document.querySelector('.fichePersonnel').href = "pdf/fichepersonnel/"+row.dataset.id;
        document.querySelector('.echelon').href = "echelon/"+row.dataset.id;
        document.querySelector('.promos').href = "promos/"+row.dataset.id;
      }else{
        document.querySelector('.certificatTravail').href = "pdf/certificatTravail/"+row.dataset.id
      }
      document.querySelector(".numero").innerHTML = row.dataset.numero;

      document.querySelector(".historique").href =
        "historique/" + row.dataset.id;
    };
  });
</script>
{% endblock script %}

templates/footer.html
<!-- Footer -->
<footer class="page-footer" style="color: #fff; padding: 30px 0">
  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-4 mt-md-0 mt-3"></div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3" />

      <!-- Grid column -->
      <div class="col-md-4 mb-md-0 mb-3" style="text-align: justify">
        <!-- Links -->

        <ul class="list-unstyled">
          <li>
            <h6>
              Adresse : Route nationale n° 75, Amizour - 06300 Bejaia, Algérie
            </h6>
          </li>
          <li>
            <h6>E-MAIL : contact@estin.dz</h6>
          </li>
          <li>
            <h6>Téléphone : 034824916</h6>
          </li>
        </ul>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 mb-md-0 mb-3"></div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
    © 2021 Copyright:
    <a href="https://mdbootstrap.com/"> </a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/home.html
{% extends 'main.html' %} {%block title%}Home{%endblock%} {%block body %}
<div class="container home">
  <div class="row">
    {% if request.user.has_perm %}
    <div class="col">
      <a href="{% url 'users' %}">
        <div>
          <img
            src="https://icon-library.com/images/user-group-icon/user-group-icon-4.jpg"
            alt="users"
          />
          <h1>Espace utilisateurs</h1>
        </div>
      </a>
    </div>
    {% endif %}
    <div class="col">
      <a href="{% url 'ats' %}">
        <div>
          <img
            src="https://mhmi.net/wp-content/uploads/2020/07/invoice-flat-icon-payment-bill-600w-741679549.jpg"
            alt="users"
          />
          <h1>Espace ATS</h1>
        </div>
      </a>
    </div>
  </div>
</div>
{% endblock%}

templates/users.html
{% extends 'main.html' %} {%block title%}Utilisateurs{%endblock%} {%block body%}
<div class="container home" style="height: auto">
  <div class="row" style="margin-left: 3px">
    <form action="{% url 'users' %}" method="get">
      <div class="input-group search">
        <div class="form-outline">
          <input type="search" name="search" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </form>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">NOM</th>
          <th scope="col">PRENOM</th>
          <th scope="col">FONCTION</th>
          <th scope="col">NUMERO</th>
          <th scope="col">SUPPRIMER</th>
          <th scope="col">MODIFIER</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{user.id}}</td>
          <td>{{user.nom}}</td>
          <td>{{user.prenom}}</td>
          <td>{{user.get_fonction_display}}</td>
          <td>{{user.numero}}</td>
          <td>
            <!-- Button trigger modal -->
            <button
              type="button"
              class="btn btn"
              data-bs-toggle="modal"
              data-bs-target="#users{{user.id}}"
            >
              <i class="fa fa-trash" aria-hidden="true" style="color: red"></i>
            </button>

            <!-- Modal -->
            <div
              class="modal fade"
              id="users{{user.id}}"
              tabindex="-1"
              aria-labelledby="exampleModalLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                      Confirmer la supression
                    </h5>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      Annuler
                    </button>
                    <a
                      href="{% url 'supprimer' user.id %}"
                      class="btn btn-danger"
                    >
                      Confirmer
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </td>
          <td>
            <a href="{% url 'edite' user.id %}">
              <i class="fas fa-edit" style="color: green"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
        <!--hh-->
        {% if is_paginated %}
        <tr>
          <td colspan="7" class="table">
            <div
              style="
                display: flex;
                justify-content: center;
                align-items: center;
              "
            >
              {% if users.has_previous %}
              <div>
                <a href="?page={{users.previous_page_number}}">
                  <i class="fa fa-caret-left fa-2x" aria-hidden="true"></i>
                </a>
              </div>

              {% endif %}
              <div>
                <span style="background-color: #e8e5e5; border-radius: 20px"
                  >{{page_number}}</span
                >
              </div>

              <!--ll-->
              {% if users.has_next %}
              <div>
                <a href="?page={{users.next_page_number}}">
                  <i class="fa fa-caret-right fa-2x" aria-hidden="true"></i>
                </a>
              </div>

              {% endif %}
            </div>
          </td>
        </tr>

        {% endif %}
        <tr>
          <td colspan="7" class="table-active add">
            <a href="{% url 'ajout' %}">
              <i class="fa fa-plus" aria-hidden="true"></i>
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock%} {% block script %}
<script>
  document.querySelector(".add").onclick = () => {
    window.location.href = "{% url 'ajout' %}";
  };
</script>
{% endblock script %}