mA/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myapp.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from django.conf import settings


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)

		user.fonction = 'C'
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.fonction = "A"
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


FONCTION = (
	('A','SOUS DIRECTEUR PERSONNEL'),
	('C','CHEF ATS')
)

class Utilisateur(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    numero = models.CharField(max_length=10)
    fonction = models.CharField(max_length=1,choices=FONCTION,null=False)
    profile_pic = models.ImageField(default="profile.jpg", null=True, blank=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)



    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    def __str__(self):
	    return self.username

	# For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, obj=None):
	    return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
	    return True



FONCTION2 = (
    ('R','rien'),
    ('D',"directeur"),
    ('DA','directeur adjoint'),
    ('SD','sous-directeur'),
    ('SDF','sous-directeur de finances')
)

SITUATION_FAMILIALE = (
    ('C','celibataire'),
    ('M','marié'),
    ('D',"devorcé")
)

NATURE = (
    ('S','stagiaire'),
    ('F','fonctionnaire')
)


MOTIF = (
    ('N','None'),
    ('DE','Décédé'),
    ('M','Mutation'),
    ('DI','Dimensionné'),
    ('R','Retraité')
)

DECISION = (
    ('N','None'),
    ('A','Automatique'),
    ('C','Commission')
)

ALERT = (
    ('0','0'),
    ('1',"1 an"),
    ('2','2 ans'),
    ('3','3 ans'),
    ('4','4 ans'),
    ('5','5 ans'),
    ('6','6 ans'),
)

class Employee(models.Model):
    image = models.ImageField(default="profile.jpg", null=True, blank=True)
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    function=models.CharField(choices=FONCTION2 , max_length=3,null=True)
    numero =models.CharField(max_length=10,null=True)
    naissance=models.DateField()
    adresse = models.CharField(max_length=200,null=True)
    email = models.EmailField(max_length=200,null=True)
    situation = models.CharField(choices=SITUATION_FAMILIALE , max_length=1,null=True)
    # date recrutememtn
    date_joined = models.DateField()
    date_recretment  = models.DateField()
    Nenfant=models.IntegerField()
    nature=models.CharField(choices=NATURE , max_length=1,null=True)
    numccp=models.IntegerField()
    numss=models.IntegerField()
    Xfonctionnair = models.BooleanField(default=False)
    motif = models.CharField(default="N", choices=MOTIF,max_length=2)
    date_supression = models.DateField(auto_now_add=True,null=True,blank=True)
    comentaire = models.TextField(null=True,blank=True)
    date_effet = models.DateField(blank=True,null=True)
    cheked = models.BooleanField(default=False)
    is_greater_than_2 = models.BooleanField(default=False)
    is_greater_than_10 = models.BooleanField(default=False)
    decision = models.CharField(default="N",max_length=1,choices=DECISION) 
    color = models.CharField(max_length=10,null=True,blank=True)
    checked = models.BooleanField(default=False)
    date = models.DateField(blank=True,null=True)
    alerte = models.CharField(default="0", max_length=1,choices=ALERT)
    def __str__(self):
        return self.nom

FILIERE = (
        ('0','Filiere'),
        ('A','Administration'),
        ('I','Informatique'),
    )

GRADES = (
    # default
    ('0','Grade'),
    # Adminitration
    ('GA','Adimistrateur'),
    ('GAP','Administrateur principal'),
    ('GAC','Administrateur conseiller'),
    ('GAA',"Attaché d'administration"),
    ('GPA',"Attaché principale d'administration"),
    ('AB',"Agents de bureau"),
    ('AA',"Agent d'administration"),
    ('APA',"Agent principale d'administration"),
    ('AS',"Agents de saisie"),
    ('S',"Secretaire"),
    ("SD","Secretaire de direction"),
    ('SPD',"Secretaire principale de direction"),
    ('ACA',"Aide comptable administrative"),
    ("CA","Compatble administrative"),
    ('CAP',"Comptable administrative principale"),
    #Informatique
    ("IA","Ingenieur d'application"),
    ("IE","Ingenieur d'etat"),
    ("IP","Ingenieur principal"),
    ("IC","Ingenieur en chef"),
    ("T","Technicien"),
    ("TS","Technicien superieur"),
    ("AT","Adjoint technique"),
    ("AST","Agent technique")
)

CORPS = (
    # default
    ("0","COPRS"),
    #admnisi
    ("A","Adminstrateurs"),
    ("AD","Attachés d'dministrations"),
    ("AA","Agents d'dministrations"),
    ("S","Secretaire"),
    ("CA","Comptables administratifs"),
    # info
    ("I","Ingenieurs"),
    ("T","Techniciens"),
    ("AT","Adjoint techniques"),
    ("AST","Agents techniques"),
)



POSTES = (
    ('R','Rien'),
    ('D','Directeur'),
    ('DA','Directeur adjoint'),
    ('CD','Chef de departement'),
    ('SG','Secretaire generale'),
    ('DB','Directeur de la bibliotheque'),
    ('SDPF','Sous directeur des personnels et de la formation'),
    ('SDFM','Sous directeur des finances et de moyens'),
    ('RCIA',"Responsable de centre d'impression et d'audiovisuel"),
    ('RCSI',"Responsable de centre de systemes et reseaux d'informations"),
    ("RHT","Responsable de hall de technologies"),
    ("RFP","Responsable de la forme de production")
)

PROMO = (
    ('0','0'),
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
    ('13','13'),
    ('14','14'),
    ('15','15'),
    ('16','16'),
)

ECHELON = (
    ('0','0'),
    ('1','1er'),
    ('2','2eme'),
    ('3','3eme'),
    ('4','4eme'),
    ('5','5eme'),
    ('6','6eme'),
    ('7','7eme'),
    ('8','8eme'),
    ('9','9eme'),
    ('10','10eme'),
    ('11','11eme'),
    ('12','12eme'),
)

class Paie(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    filiere = models.CharField(default='0',max_length=1,choices=FILIERE)
    grade = models.CharField(default="0",max_length=3,choices=GRADES)
    corps = models.CharField(default="0",max_length=3,choices=CORPS)
    categorie = models.IntegerField(default=0)
    indice = models.IntegerField(default=0)
    salaire = models.FloatField(default=0.0)
    poste_occupe = models.CharField(default='R',max_length=4,choices=POSTES)
    indiciaire = models.FloatField(default=0.0)
    categorie_promo = models.CharField(default="0",max_length=2,choices=PROMO)
    groupe = models.CharField(default="None",max_length=10)
    indice_minimale = models.FloatField(default=0.0)
    indice_echelon = models.CharField(default="0",max_length=2,choices=ECHELON)
    echelon = models.IntegerField(default=0)
    grille = models.FloatField(default=0.0) 
    indemite_sac = models.FloatField(default=0.0)   
    indemite_stc = models.FloatField(default=0.0)
    securite = models.FloatField(default=0.0)
    salaire_brut = models.FloatField(default=0.0)
    indimnite_transport = models.IntegerField(default=0)
    indimnite_panier = models.IntegerField(default=0)
    totale_brute_imposable_irg = models.FloatField(default=0.0)
    irg = models.IntegerField(default=0)
    allocation_familiale = models.IntegerField(default=0)
    totale = models.FloatField(default=0.0)
    nombre_travaille = models.IntegerField(default=0)
    nombre_absence = models.IntegerField(default=0)
    salaire_net = models.FloatField(default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.employee.nom




NATUREC = (
    ('M','Maladie'),
    ('A','Annuel'),
    ('E','Exceptionnel')
)

class Conge(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    debut = models.DateField(null=True,blank=True)
    fin = models.DateField(null=True,blank=True)
    nombre = models.CharField(max_length=50,null=True,blank=True)
    nature = models.CharField(null=True,blank=True,max_length=1,choices=NATUREC)
    retour = models.DateTimeField(null=True,blank=True)
    commentaire = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.employee.nom



TRIMESTRE = (
    ("1","1er trimestre"),
    ("2","2eme trimestre"),
    ('3','3eme trimestre'),
    ('4',"4eme trimestre")
)


class Prime(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    note_prime = models.IntegerField(blank=True,null=True)
    commentaire = models.TextField(blank=True,null=True)
    trimestre = models.CharField(max_length=1,choices=TRIMESTRE,blank=True,null=True)
    date = models.DateField(blank=True,null=True)
    salaire_principal = models.FloatField() 
    salaire_brut_mensulle = models.FloatField() 

templates/pdf/conge.html
{% extends 'pdf/base.html' %}

<!--title-->

{% block title %}conge{% endblock title %}
<!--body-->
{% block body %}
<div class="titlepdf">
  <h1>TITRE DE CONGE</h1>
</div>
<div class="congebody">
  -Nous soussignes, <strong>Mr {{user.nom}} {{user.prenom}}</strong> , agissant
  en qualite de <strong>{{user.get_fonction_display}}</strong> dans l'ecole
  ESTIN, attestons que:
  <div class="person">
    <div>Nom: <strong>{{employee.nom}}</strong></div>
    <div>Prenom: <strong>{{employee.prenom}}</strong></div>
    <div>Fonction: <strong>{{employee.get_function_display}}</strong></div>
    <div>Nombre de jours de conge: <strong>{{conge.nombre}}</strong></div>
    <div>Nature de conge: <strong>{{conge.get_nature_display}}</strong></div>
    <div>
      Date de depart de conge: <strong>{{conge.debut |date:"d/m/Y"}}</strong> au
      <strong>{{conge.fin |date:"d/m/Y"}}</strong>
    </div>
    <div>
      Date de retour du conge: <strong>{{conge.retour|date:"d/m/Y"}}</strong>
    </div>
  </div>
</div>
<div class="congebottom">
  le present titre de conge est delivre a l'interesse(e) pour servir et valider
  ce que de droit .
</div>

<div class="signature1">fait a Amizour, le: {{current}}</div>
<div class="signature">Signature</div>
{% endblock body %}

templates/pdf/fichepersonnel.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/pdfstyles.css' %}"
    />
    <script
      src="https://kit.fontawesome.com/3acc62aaef.js"
      crossorigin="anonymous"
    ></script>
    <style type="text/css">
      @page {
        @frame header_frame {
          /* Static Frame */
          -pdf-frame-content: header_content;
          left: 50pt;
          width: 512pt;
          top: 50pt;
          height: 40pt;
        }
        @frame content_frame {
          /* Content Frame */
          left: 50pt;
          width: 512pt;
          top: 90pt;
          height: 632pt;
          -pdf-frame-border: 1;
          margin:1cm;
          margin-top:0;
          padding:1cm;
        }
        @frame footer_frame {
          /* Another static Frame */
          -pdf-frame-content: footer_content;
          left: 50pt;
          width: 512pt;
          top: 772pt;
          height: 20pt;
        }
      }
    </style>
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    
    <!-- Content for Static Frame 'header_frame' -->
    <div id="header_content">
        <table id="upp">
            <tr>
                <td>
                    <div class="alignleft">
                        {{current}}
                    </div>
                </td>
                <td></td>
                <td></td>
                <td> <h4>Fiche Personnel</h4>  </td>
                <td></td>
                <td></td>
                <td>
                </td>
            </tr>
        </table>
    </div>

    <!-- Content for Static Frame 'footer_frame' -->
    <div id="footer_content">
          Adresse: route nationale n75 Amizour -06300 Bezoia, Algerie E-Mail:
          contact@estin.ds Tel: 034824916 Numero SS Employeur:
          {{employee.numss}}
        <pdf:pagenumber>
        of <pdf:pagecount>
    </div>

    <!-- HTML Content -->
    <div>
        <table id="upp">
            <tr>
                <td>
                    <div class="alignleft">
                        <img
                            src="https://estin.dz/wp-content/uploads/2020/11/cropped-estin_logo-mini-2-2.jpg"
                            alt="logo"
                        />
                    </div>
                </td>
                <td></td>
            <td></td>
            <td></td>
            <td class="alignright">
                <img style="height:45mm; width:35mm;" src="https://thumbs.dreamstime.com/b/default-avatar-profile-flat-icon-social-media-user-vector-portrait-unknown-human-image-default-avatar-profile-flat-icon-184330869.jpg" alt="photo">
            </td>
            </tr>
        </table>
    </div>
    <div style="width:100%;text-align:center;">
        <h4 style="font-size:30px">Fiche Personnel</h4>
    </div>
    <div style='font-size:14px; padding-top:4px;'>
        <table style="width:100%">
            <tr>
                <td style="width:49%;">Nom</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.nom}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Prenom</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.prenom}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Fonction</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.get_function_display}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Telephone</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.numero}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Email</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.email}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Adresse</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.adresse}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Date de naissance</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.naissance | date:"d/m/Y"}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Situation familiale</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.situation}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Date de recretement</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.date_recretment | date:"d/m/Y"}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Date d'instalation</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.date_joined | date:"d/m/Y"}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Nature</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.get_nature_display}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Code de CCP</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.numccp}}</td>
            </tr>
            <tr>
                <td style="width:49%;">Numero de securite sociale</td>
                <td style="width:2%">:</td>
                <td style="width:49%">{{employee.numss}}</td>
            </tr>
        </table>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/pdf/paie.html
{% extends 'pdf/base.html' %}

<!--title-->

{% block title %}Fiche de paie{% endblock title %}
<!--body-->
{% block body %}
<div
  class="titlepdf"
  style="padding-top: 5px; padding-bottom: 0px; margin: 0px"
>
  <h1 style="font-size: 22px">Bulltin de paie</h1>
</div>

<div
  class="tt"
  style="width: 100%; text-align: right; padding-top: 0px:margin:0px"
>
  Paie : {{month}}/{{year}}
</div>
<div class="con">
  <div class="top">
    <table id="upp" class="border">
      <tr>
        <td style="border: none"></td>
        <td class="center1" style="padding-top: 5px; width: 75%">
          <p>Nome: <strong>{{employee.nom}}</strong></p>
        </td>
        <td class="center2" style="padding-top: 5px; width: 75%">
          <p>Prenom: <strong>{{employee.prenom}}</strong></p>
        </td>
        <td style="border: none; padding-top: 5px"></td>
      </tr>

      <tr>
        <td style="border: none; padding-top: 5px"></td>
        <td class="center11" style="width: 75%; padding-top: 5px">
          <p>
            Date de naissance:
            <strong>{{employee.naissance |date:"d/m/Y"}}</strong>
          </p>
        </td>
        <td class="center22" style="width: 75%; padding-top: 5px">
          <p>Mode de paiement: <strong>B.N.A</strong></p>
        </td>
        <td style="border: none; padding-top: 5px"></td>
      </tr>

      <tr>
        <td style="border: none; padding-top: 5px"></td>
        <td
          class="center11"
          style="padding-top: 5px; border-bottom: solid 1px #000"
        >
          <p>Adresse: <strong>{{employee.adresse}}</strong></p>
        </td>
        <td
          class="center22"
          style="padding-top: 5px; border-bottom: solid 1px #000"
        >
          <p>Telephone: <strong>{{employee.numero}}</strong></p>
        </td>
        <td style="border: none; padding-top: 5px"></td>
      </tr>
    </table>
  </div>
</div>

<div class="center">
  <table id="upp" style="border: 1px solid #000">
    <thead>
      <tr>
        <th>Trv</th>
        <th>Num S.S</th>
        <th>Enf</th>
        <th>S.F</th>
        <th>Ech</th>
        <th>Foncion</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="ee">{{paie.nombre_travaille}} jour(s)</td>
        <td class="ee">{{employee.numss}}</td>
        <td class="ee">{{employee.Nenfant}}</td>
        <td class="ee">{{employee.get_situation_display}}</td>
        <td class="ee">{{paie.echelon}}</td>
        <td class="ee">{{employee.get_function_display}}</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="fiche" style="margin-top: 10px">
  <table id="upp" style="border: 1px solid #000">
    <thead>
      <tr>
        <th style="padding-top: 5px">Libelle</th>
        <th style="width: 15%; padding-top: 5px">TOTAL</th>
      </tr>
    </thead>
    <tbody>
      <!--first-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          SAL.BASE :
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.salaire |floatformat:2 }}
        </td>
      </tr>
      <!--Second-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          BONIF.IND:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.indiciaire |floatformat:2 }}
        </td>
      </tr>
      <!--trois-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          IND.MIN:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.indice_minimale |floatformat:2 }}
        </td>
      </tr>
      <!--Second-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          G.I.T:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.grille |floatformat:2 }}
        </td>
      </tr>
      <!--5-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          I.SAC:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.indemite_sac |floatformat:2 }}
        </td>
      </tr>
      <!--6-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          I.STC:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.indemite_stc |floatformat:2 }}
        </td>
      </tr>
      <!--Second-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          RETS.S9%:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{securite |floatformat:2 }}
        </td>
      </tr>
      <!--Second-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td
          style="
            padding-top: 5px;
            padding-right: 4px;
            text-align: right;
            border-right: none;
          "
        >
          TOTAL BRUT IMPOSABLE:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.salaire_brut |floatformat:2 }}
        </td>
      </tr>
      <!--10-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          I.TRA:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.indimnite_transport |floatformat:2 }}
        </td>
      </tr>
      <!--11-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          I.PAN:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.indimnite_panier |floatformat:2 }}
        </td>
      </tr>
      <!--Second-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td
          style="
            padding-top: 5px;
            padding-right: 4px;
            text-align: right;
            border-right: none;
          "
        >
          TOTAL BRUT IMP IRG:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.totale_brute_imposable_irg |floatformat:2 }}
        </td>
      </tr>
      <!--10-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          RET I.R.G:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.irg |floatformat:2 }}
        </td>
      </tr>
      <!--10-->
      <!--11-->
      <tr
        style="
          border: none;
          border-left: 1px solid #000;
          border-right: 1px solid #000;
        "
      >
        <td style="padding-top: 5px; padding-left: 4px; border-right: none">
          ALL.FAM:
        </td>
        <td style="padding-top: 5px; width: 15%; border-left: none" class="ee">
          {{paie.allocation_familiale |floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
</div>

<div class="bottom1" style="margin-top: 10px">
  <table id="upp" style="border: 1px solid #000">
    <thead>
      <tr>
        <th style="padding-top: 5px">TOTALE RETENUES:</th>
        <th style="width: 15%; padding-top: 5px">{{totale |floatformat:2 }}</th>
      </tr>
    </thead>
  </table>
</div>

<div class="bottom12" style="margin-top: 10px">
  <table id="upp" style="border: 1px solid #000">
    <thead>
      <tr>
        <th style="padding-top: 5px">SALAIRE NET:</th>
        <th style="width: 15%; padding-top: 5px">
          {{paie.salaire_net |floatformat:2 }}
        </th>
      </tr>
    </thead>
  </table>
</div>

<div class="signature1" style="padding-top: 20px">
  fait a Amizour, le: {{current}}
</div>
<div class="signature">Signature</div>

{% endblock body %}